import MenuManagement from "../pages/menumanagement/MenuManagement";

export const storemanagementdata = [
  {
    storeid: "#5689336",
    storename: "Main Street Market",
    city: "Springfield",
    address: "123 Main St",
    contactnumber: "555-1234",
    openinghouse: "9 AM - 9 PM",
    status: "Active",
  },
  {
    storeid: "#5689336",
    storename: "Main Street Market",
    city: "Springfield",
    address: "123 Main St",
    contactnumber: "555-1234",
    openinghouse: "9 AM - 9 PM",
    status: "Active",
  },
  {
    storeid: "#5689336",
    storename: "Main Street Market",
    city: "Springfield",
    address: "123 Main St",
    contactnumber: "555-1234",
    openinghouse: "9 AM - 9 PM",
    status: "Active",
  },
  {
    storeid: "#5689336",
    storename: "Main Street Market",
    city: "Springfield",
    address: "123 Main St",
    contactnumber: "555-1234",
    openinghouse: "9 AM - 9 PM",
    status: "Active",
  },
  {
    storeid: "#5689336",
    storename: "Main Street Market",
    city: "Springfield",
    address: "123 Main St",
    contactnumber: "555-1234",
    openinghouse: "9 AM - 9 PM",
    status: "Active",
  },
  {
    storeid: "#5689336",
    storename: "Main Street Market",
    city: "Springfield",
    address: "123 Main St",
    contactnumber: "555-1234",
    openinghouse: "9 AM - 9 PM",
    status: "Active",
  },
  {
    storeid: "#5689336",
    storename: "Main Street Market",
    city: "Springfield",
    address: "123 Main St",
    contactnumber: "555-1234",
    openinghouse: "9 AM - 9 PM",
    status: "Active",
  },
  {
    storeid: "#5689336",
    storename: "Main Street Market",
    city: "Springfield",
    address: "123 Main St",
    contactnumber: "555-1234",
    openinghouse: "9 AM - 9 PM",
    status: "Active",
  },
];

export const menumanagementdata = [
  {
    productid: "#12345",
    productname: "Coffee",
    category: "Coffee",
    Price: "$9.99",
    addoneavailable: "Extra Sugar",
    lastupdate: "27.08.2025",
    status: "Available",
  },
  {
    productid: "#12345",
    productname: "Coffee",
    category: "Coffee",
    Price: "$9.99",
    addoneavailable: "Extra Sugar",
    lastupdate: "27.08.2025",
    status: "Available",
  },
  {
    productid: "#12345",
    productname: "Coffee",
    category: "Coffee",
    Price: "$9.99",
    addoneavailable: "Extra Sugar",
    lastupdate: "27.08.2025",
    status: "Available",
  },
  {
    productid: "#12345",
    productname: "Coffee",
    category: "Coffee",
    Price: "$9.99",
    addoneavailable: "Extra Sugar",
    lastupdate: "27.08.2025",
    status: "unavailable",
  },
  {
    productid: "#12345",
    productname: "Coffee",
    category: "Coffee",
    Price: "$9.99",
    addoneavailable: "Extra Sugar",
    lastupdate: "27.08.2025",
    status: "unavailable",
  },
  {
    productid: "#12345",
    productname: "Coffee",
    category: "Coffee",
    Price: "$9.99",
    addoneavailable: "Extra Sugar",
    lastupdate: "27.08.2025",
    status: "Unavailable",
  },
  {
    productid: "#12345",
    productname: "Coffee",
    category: "Coffee",
    Price: "$9.99",
    addoneavailable: "Extra Sugar",
    lastupdate: "27.08.2025",
    status: "Available",
  },
  {
    productid: "#12345",
    productname: "Coffee",
    category: "Coffee",
    Price: "$9.99",
    addoneavailable: "Extra Sugar",
    lastupdate: "27.08.2025",
    status: "Available",
  },
];

export const offermanagementdata = [
  {
    offerid: "#12345",
    title: "Public",
    offertype: "Sophia Clark",
    discount: "20%",
    validity: "07/01/2024 - 07/31/2024",
    Applicablestores: "All Stores",
    status: "Active",
  },
  {
    offerid: "#12345",
    title: "Public",
    offertype: "Sophia Clark",
    discount: "20%",
    validity: "07/01/2024 - 07/31/2024",
    Applicablestores: "All Stores",
    status: "Inactive",
  },
  {
    offerid: "#12345",
    title: "Public",
    offertype: "Sophia Clark",
    discount: "20%",
    validity: "07/01/2024 - 07/31/2024",
    Applicablestores: "All Stores",
    status: "Inactive",
  },
  {
    offerid: "#12345",
    title: "Public",
    offertype: "Sophia Clark",
    discount: "20%",
    validity: "07/01/2024 - 07/31/2024",
    Applicablestores: "All Stores",
    status: "Inactive",
  },
  {
    offerid: "#12345",
    title: "Public",
    offertype: "Sophia Clark",
    discount: "20%",
    validity: "07/01/2024 - 07/31/2024",
    Applicablestores: "All Stores",
    status: "Active",
  },
  {
    offerid: "#12345",
    title: "Public",
    offertype: "Sophia Clark",
    discount: "20%",
    validity: "07/01/2024 - 07/31/2024",
    Applicablestores: "All Stores",
    status: "Active",
  },
  {
    offerid: "#12345",
    title: "Public",
    offertype: "Sophia Clark",
    discount: "20%",
    validity: "07/01/2024 - 07/31/2024",
    Applicablestores: "All Stores",
    status: "Active",
  },
  {
    offerid: "#12345",
    title: "Public",
    offertype: "Sophia Clark",
    discount: "20%",
    validity: "07/01/2024 - 07/31/2024",
    Applicablestores: "All Stores",
    status: "Active",
  },
];

export const nearbyattractionsdata = [
  {
    attractionid: "#12345",
    title: "Central Park",
    citylocation: "New York",
    linkedstore: "Store A",
    addon: "28.08.2025",
    status: "Active",
  },
  {
    attractionid: "#12345",
    title: "Central Park",
    citylocation: "New York",
    linkedstore: "Store A",
    addon: "28.08.2025",
    status: "Inactive",
  },
  {
    attractionid: "#12345",
    title: "Central Park",
    citylocation: "New York",
    linkedstore: "Store A",
    addon: "28.08.2025",
    status: "Inactive",
  },
  {
    attractionid: "#12345",
    title: "Central Park",
    citylocation: "New York",
    linkedstore: "Store A",
    addon: "28.08.2025",
    status: "Inactive",
  },
  {
    attractionid: "#12345",
    title: "Central Park",
    citylocation: "New York",
    linkedstore: "Store A",
    addon: "28.08.2025",
    status: "Active",
  },
  {
    attractionid: "#12345",
    title: "Central Park",
    citylocation: "New York",
    linkedstore: "Store A",
    addon: "28.08.2025",
    status: "Active",
  },
  {
    attractionid: "#12345",
    title: "Central Park",
    citylocation: "New York",
    linkedstore: "Store A",
    addon: "28.08.2025",
    status: "Active",
  },
  {
    attractionid: "#12345",
    title: "Central Park",
    citylocation: "New York",
    linkedstore: "Store A",
    addon: "28.08.2025",
    status: "Active",
  },
];

export const rolesdata = [
  {
    name: "john",
    roles: "Admin",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    createdby: "Super Admin",
  },
];

export const Userdata = [
  {
    name: "john",
    roles: "Admin",
    phonenumber: "9568479534",
    email: "ahgdkej@gmail.com",
    status: "Active",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    phonenumber: "9568479534",
    email: "ahgdkej@gmail.com",
    status: "Active",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    phonenumber: "9568479534",
    email: "ahgdkej@gmail.com",
    status: "Active",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    phonenumber: "9568479534",
    email: "ahgdkej@gmail.com",
    status: "Active",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    phonenumber: "9568479534",
    email: "ahgdkej@gmail.com",
    status: "Active",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    phonenumber: "9568479534",
    email: "ahgdkej@gmail.com",
    status: "Active",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    phonenumber: "9568479534",
    email: "ahgdkej@gmail.com",
    status: "Active",
    createdby: "Super Admin",
  },
  {
    name: "john",
    roles: "Admin",
    phonenumber: "9568479534",
    email: "ahgdkej@gmail.com",
    status: "Active",
    createdby: "Super Admin",
  },
];

export const tablesdata = [
  {
    orderid: "#12345",
    storename: "Main Street Dinner",
    username: "Sophia Clark",
    ordertype: "Dine-In",
    paymentmode: "Card",
    amount: "$25.00",
    ordertime: "10.15 AM",
    status: "Completed",
  },
  {
    orderid: "#12345",
    storename: "Main Street Dinner",
    username: "Sophia Clark",
    ordertype: "Dine-In",
    paymentmode: "Card",
    amount: "$25.00",
    ordertime: "10.15 AM",
    status: "Pending",
  },
  {
    orderid: "#12345",
    storename: "Main Street Dinner",
    username: "Sophia Clark",
    ordertype: "Dine-In",
    paymentmode: "Card",
    amount: "$25.00",
    ordertime: "10.15 AM",
    status: "In-Progress",
  },
  {
    orderid: "#12345",
    storename: "Main Street Dinner",
    username: "Sophia Clark",
    ordertype: "Dine-In",
    paymentmode: "Card",
    amount: "$25.00",
    ordertime: "10.15 AM",
    status: "Completed",
  },
  {
    orderid: "#12345",
    storename: "Main Street Dinner",
    username: "Sophia Clark",
    ordertype: "Dine-In",
    paymentmode: "Card",
    amount: "$25.00",
    ordertime: "10.15 AM",
    status: "Completed",
  },
  {
    orderid: "#12345",
    storename: "Main Street Dinner",
    username: "Sophia Clark",
    ordertype: "Dine-In",
    paymentmode: "Card",
    amount: "$25.00",
    ordertime: "10.15 AM",
    status: "In-progress",
  },
  {
    orderid: "#12345",
    storename: "Main Street Dinner",
    username: "Sophia Clark",
    ordertype: "Dine-In",
    paymentmode: "Card",
    amount: "$25.00",
    ordertime: "10.15 AM",
    status: "Pending",
  },
];

export const usermanagementdata = [
  {
    userid: "#5689336",
    name: "Aarnav",
    phonenumber: "0000 0000",
    email: "sophia.clark@gmailcom",
    walletbalace: "$500",
    membershiptype: "Premium",
    status: "Active",
  },
  {
    userid: "#12345",
    name: "Sophia Clark",
    phonenumber: "9568479534",
    email: "ahgdkej@gmail.com",
    walletbalace: "$25.00",
    membershiptype: "Free",
    status: "Blocked",
  },
  {
    userid: "#12345",
    name: "Sophia Clark",
    phonenumber: "9568479534",
    email: "ahgdkej@gmail.com",
    walletbalace: "$25.00",
    membershiptype: "Free",
    status: "Blocked",
  },
  {
    userid: "#5689336",
    name: "Aarnav",
    phonenumber: "0000 0000",
    email: "sophia.clark@gmailcom",
    walletbalace: "$500",
    membershiptype: "Premium",
    status: "Active",
  },
  {
    userid: "#5689336",
    name: "Aarnav",
    phonenumber: "0000 0000",
    email: "sophia.clark@gmailcom",
    walletbalace: "$500",
    membershiptype: "Premium",
    status: "Active",
  },
  {
    userid: "#5689336",
    name: "Aarnav",
    phonenumber: "0000 0000",
    email: "sophia.clark@gmailcom",
    walletbalace: "$500",
    membershiptype: "Premium",
    status: "Active",
  },
  {
    userid: "#5689336",
    name: "Aarnav",
    phonenumber: "0000 0000",
    email: "sophia.clark@gmailcom",
    walletbalace: "$500",
    membershiptype: "Premium",
    status: "Active",
  },
  {
    userid: "#5689336",
    name: "Aarnav",
    phonenumber: "0000 0000",
    email: "sophia.clark@gmailcom",
    walletbalace: "$500",
    membershiptype: "Premium",
    status: "Active",
  },
  
];

export const ScratchManagementdata = [

    {
        cardid:"A1B2C3",
        type:"Discount",
        elligibility:"All Users",
        expirydate:"27.08.2025",
        status:"Active",
    },
    {
        cardid:"A1B2C3",
        type:"Discount",
        elligibility:"All Users",
        expirydate:"27.08.2025",
        status:"Active",
    },
    {
        cardid:"A1B2C3",
        type:"Discount",
        elligibility:"All Users",
        expirydate:"27.08.2025",
        status:"Active",
    },
    {
        cardid:"A1B2C3",
        type:"Discount",
        elligibility:"All Users",
        expirydate:"27.08.2025",
        status:"Expired",
    },
    {
        cardid:"A1B2C3",
        type:"Discount",
        elligibility:"All Users",
        expirydate:"27.08.2025",
        status:"Active",
    },
    {
        cardid:"A1B2C3",
        type:"Discount",
        elligibility:"All Users",
        expirydate:"27.08.2025",
        status:"Expired",
    },
    
    

]

export const walletmanagementdata = [
    {
        userid:"#12345",
        name:"Sophia Clark",
        currentbalance:"$500",
        lasttopup:"27.08.2025",
        rechargemode:"Manual",
    },
    {
        userid:"#12345",
        name:"Sophia Clark",
        currentbalance:"$500",
        lasttopup:"27.08.2025",
        rechargemode:"Manual",
    },
    {
        userid:"#12345",
        name:"Sophia Clark",
        currentbalance:"$500",
        lasttopup:"27.08.2025",
        rechargemode:"Manual",
    },
    {
        userid:"#12345",
        name:"Sophia Clark",
        currentbalance:"$500",
        lasttopup:"27.08.2025",
        rechargemode:"Manual",
    },
    {
        userid:"#12345",
        name:"Sophia Clark",
        currentbalance:"$500",
        lasttopup:"27.08.2025",
        rechargemode:"Manual",
    },
    {
        userid:"#12345",
        name:"Sophia Clark",
        currentbalance:"$500",
        lasttopup:"27.08.2025",
        rechargemode:"Manual",
    },
    

]